dependencies:
  uv_project: ../common/cant-be-late-simulator
datasets:
  - type: local_tar
    path: ../common/real_traces.tar.gz
    target: ../common/cant-be-late-simulator/data
    expected_glob: "real/ddl=search+task=48+overhead=*/real/*/traces/random_start/*.json"
tag: os
